name: Go
on: 
- push
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.12, 1.13]
        os: [ubuntu-latest, windows-latest, maxOS-latest]
    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Go vet
      run: go vet -v ./...
    - name: Go test
      run: go test -v ./...
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
    - name: Build
      run: |
        go install github.com/mitchellh/gox
        VER=$(git describe --tags)
        DATE=$(date)
        gox -ldflags="-X 'github.com/screepers/screeps-launcher/v1/version.BuildTime=$DATE' -X 'github.com/screepers/screeps-launcher/v1/version.BuildVersion=${VER}'" -os="linux darwin windows" -arch="amd64" -output="dist/screeps-launcher_${VER}_{{.OS}}_{{.Arch}}" ./cmd/screeps-launcher/
        gox -ldflags="-X 'github.com/screepers/screeps-launcher/v1/version.BuildTime=$DATE' -X 'github.com/screepers/screeps-launcher/v1/version.BuildVersion=${VER}'" -os="linux" -arch="arm arm64" -output="dist/screeps-launcher_${VER}_{{.OS}}_{{.Arch}}" ./cmd/screeps-launcher/
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
